"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import GlassCard from "@/app/admin/_components/GlassCard";
import { Field, Input, Select, Status, Textarea, buttonClass } from "@/app/admin/_components/FormParts";
import { api, Category, Product } from "@/app/admin/_lib/api";

const schema = z.object({ name: z.string().min(1).max(100), price: z.number().positive(), qty: z.number().int().positive(), description: z.string().optional(), categoryId: z.number().int().positive().optional() });
type ProductForm = z.infer<typeof schema>;

export default function AdminProductPage() {
  const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [editing, setEditing] = useState<Product>(); const [message, setMessage] = useState<string>(); const [error, setError] = useState<string>();
  const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<ProductForm>({ resolver: zodResolver(schema), defaultValues: { qty: 1 } });
  const load = () => Promise.all([api.getProducts(), api.getCategories()]).then(([p, c]) => { setProducts(p.content); setCategories(c.content); }).catch((caught: Error) => setError(caught.message));
  useEffect(() => { void load(); }, []);
  const stopEditing = () => { setEditing(undefined); reset({ name: "", price: undefined, qty: 1, description: "", categoryId: undefined }); };
  const startEditing = (product: Product) => { setEditing(product); const category = categories.find((item) => item.name === product.categoryName); reset({ name: product.name, price: Number(product.price), qty: product.qty, description: product.description ?? "", categoryId: category?.id }); };
  const submit = async (values: ProductForm) => { setError(undefined); try { if (editing) { await api.updateProduct(editing.code, values); setMessage("Product updated."); } else { if (!values.categoryId) throw new Error("Select a category."); await api.createProduct({ ...values, categoryId: values.categoryId }); setMessage("Product added to the catalog."); } stopEditing(); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not save product."); } };
  const remove = async (code: string) => { if (!window.confirm(`Delete ${code}?`)) return; try { await api.deleteProduct(code); setProducts((current) => current.filter((item) => item.code !== code)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not delete product."); } };
  return <GlassCard title="Product catalog" subtitle="Create, edit and delete product inventory"><div className="grid gap-6 xl:grid-cols-[360px_1fr]"><form onSubmit={handleSubmit(submit)} className="grid content-start gap-3 rounded-2xl border border-white/15 bg-slate-950/25 p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-white">{editing ? `Edit ${editing.code}` : "Add a product"}</h3>{editing && <button type="button" onClick={stopEditing} className="text-xs text-cyan-200">Cancel</button>}</div><Field label="Product name" error={errors.name?.message}><Input {...register("name")} /></Field><div className="grid grid-cols-2 gap-3"><Field label="Price" error={errors.price?.message}><Input type="number" step="0.01" {...register("price", { valueAsNumber: true })} /></Field><Field label="Quantity" error={errors.qty?.message}><Input type="number" {...register("qty", { valueAsNumber: true })} /></Field></div>{!editing && <Field label="Category" error={errors.categoryId?.message}><Select defaultValue="" {...register("categoryId", { valueAsNumber: true })}><option value="" className="text-slate-950">Select category</option>{categories.map((category) => <option key={category.id} value={category.id} className="text-slate-950">{category.name}</option>)}</Select></Field>}<Field label="Description"><Textarea rows={3} {...register("description")} /></Field><Status error={error} success={message} /><button disabled={isSubmitting} className={buttonClass}>{isSubmitting ? "Saving…" : editing ? "Update product" : "Add product"}</button></form><div className="overflow-hidden rounded-2xl border border-white/15"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-950/40 text-xs uppercase tracking-wide text-slate-300"><tr><th className="px-4 py-3">Product</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Stock</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{products.map((product) => <tr key={product.code} className="border-t border-white/10 text-slate-100"><td className="px-4 py-3"><p className="font-medium">{product.name}</p><p className="text-xs text-slate-400">{product.code}</p></td><td className="px-4 py-3 text-slate-300">{product.categoryName}</td><td className="px-4 py-3">${Number(product.price).toFixed(2)}</td><td className="px-4 py-3">{product.qty}</td><td className="space-x-3 px-4 py-3"><button onClick={() => startEditing(product)} className="text-xs text-cyan-200">Edit</button><button onClick={() => void remove(product.code)} className="text-xs text-rose-300">Delete</button></td></tr>)}{!products.length && <tr><td colSpan={5} className="px-4 py-10 text-center text-slate-400">No products returned by the API.</td></tr>}</tbody></table></div></div></div></GlassCard>;
}
